import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

export interface CiTemplatesOptions {
  platform?: string;
  write?: boolean;
}

const GITHUB_ACTIONS_TEMPLATE = `# .github/workflows/engagement-harness.yml
# Generated by engagement-harness ci templates --platform github
name: Engagement Harness Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: PR Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install engagement-harness
        run: npm install -g engagement-harness

      - name: Run review
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: \${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: \${{ github.repository }}
          GITHUB_PR_TITLE: \${{ github.event.pull_request.title }}
          GITHUB_PR_BODY: \${{ github.event.pull_request.body }}
        run: engagement-harness review --ci

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: engagement-harness-reports
          path: .engagement-harness/reports/
`;

const GITLAB_CI_TEMPLATE = `# .gitlab-ci.yml snippet
# Generated by engagement-harness ci templates --platform gitlab
engagement-harness-review:
  image: node:20
  stage: review
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    GITHUB_PR_NUMBER: '$CI_MERGE_REQUEST_IID'
    GITHUB_REPOSITORY: '$CI_PROJECT_PATH'
  script:
    - npm install -g engagement-harness
    - engagement-harness review --ci
  artifacts:
    when: always
    paths:
      - .engagement-harness/reports/
    expire_in: 30 days
`;

const AZURE_DEVOPS_TEMPLATE = `# azure-pipelines.yml snippet
# Generated by engagement-harness ci templates --platform azure-devops
trigger: none

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js 20'

  - script: npm install -g engagement-harness
    displayName: 'Install engagement-harness'

  - script: engagement-harness review --ci
    displayName: 'Run engagement-harness review'
    env:
      GITHUB_PR_NUMBER: $(System.PullRequest.PullRequestNumber)
      GITHUB_REPOSITORY: $(Build.Repository.Name)

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '.engagement-harness/reports/'
      ArtifactName: 'engagement-harness-reports'
    displayName: 'Upload reports'
`;

const BITBUCKET_TEMPLATE = `# bitbucket-pipelines.yml snippet
# Generated by engagement-harness ci templates --platform bitbucket
pipelines:
  pull-requests:
    '**':
      - step:
          name: Engagement Harness Review
          image: node:20
          script:
            - npm install -g engagement-harness
            - engagement-harness review --ci
          artifacts:
            - .engagement-harness/reports/**
`;

const FEEDBACK_COLLECTION_TEMPLATE = `# .github/workflows/feedback-collection.yml
# Generated by engagement-harness ci templates --platform github
name: Collect Feedback from Reactions

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  collect:
    name: Collect Feedback
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: \${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install engagement-harness
        run: npm install -g engagement-harness

      - name: Collect feedback from reactions
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          engagement-harness feedback collect \\
            --repo \${{ github.repository }} \\
            --since 7days

      - name: Commit updated feedback metrics
        run: |
          git config user.name "Engagement Harness Bot"
          git config user.email "bot@engagement-harness"
          git add .engagement-harness/feedback/ 2>/dev/null || true
          git diff --cached --quiet || git commit -m "chore: update feedback metrics from reactions"
          git push origin HEAD
`;

const TEMPLATES: Record<string, string> = {
  github: GITHUB_ACTIONS_TEMPLATE,
  gitlab: GITLAB_CI_TEMPLATE,
  'azure-devops': AZURE_DEVOPS_TEMPLATE,
  bitbucket: BITBUCKET_TEMPLATE,
};

const ALL_PLATFORMS = ['github', 'gitlab', 'azure-devops', 'bitbucket'] as const;

const OUTPUT_PATHS: Record<string, string> = {
  github: '.github/workflows/engagement-harness.yml',
  gitlab: '.gitlab-ci.yml',
  'azure-devops': 'azure-pipelines.yml',
  bitbucket: 'bitbucket-pipelines.yml',
};

export function ciTemplatesCommand(options: CiTemplatesOptions): void {
  const { platform, write } = options;

  if (!platform) {
    // No platform specified — print all templates
    for (const name of ALL_PLATFORMS) {
      console.log(`\n# ===== ${name.toUpperCase()} =====\n`);
      console.log(TEMPLATES[name]);
    }
    return;
  }

  const template = TEMPLATES[platform];
  if (!template) {
    console.error(
      `Unknown platform "${platform}". Supported platforms: ${ALL_PLATFORMS.join(', ')}`,
    );
    process.exit(1);
    return;
  }

  // GitHub: write to disk by default (--no-write to override).
  // All other platforms: print to stdout by default (--write to save).
  const shouldWrite = write ?? platform === 'github';

  if (shouldWrite) {
    const outPath = OUTPUT_PATHS[platform]!;
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, template, 'utf8');
    console.log(`Written to ${outPath}`);
    if (platform === 'github') {
      const feedbackPath = '.github/workflows/feedback-collection.yml';
      writeFileSync(feedbackPath, FEEDBACK_COLLECTION_TEMPLATE, 'utf8');
      console.log(`Written to ${feedbackPath}`);
    }
  } else {
    console.log(template);
    if (platform === 'github') {
      console.log('\n# ===== FEEDBACK COLLECTION WORKFLOW =====\n');
      console.log(FEEDBACK_COLLECTION_TEMPLATE);
    }
  }
}
