import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import path from 'node:path';

export interface CiTemplatesOptions {
  platform?: string;
  write?: boolean;
  print?: boolean;
  context?: 'client' | 'source' | 'auto';
}

export function isSourceRepo(cwd: string): boolean {
  return existsSync(path.join(cwd, 'packages', 'cli', 'package.json'));
}

const GITHUB_ACTIONS_CLIENT_TEMPLATE = `# .github/workflows/engagement-harness.yml
# Generated by engagement-harness ci templates --platform github
name: Engagement Harness Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  review:
    name: PR Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '24'

      - name: Fetch base branch
        run: git fetch origin \${{ github.base_ref }}:\${{ github.base_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Clone Engagement Harness
        run: git clone https://\${{ secrets.HARNESS_PAT }}@github.com/abhishikthmeesala-2000/harness-review.git /tmp/harness-review

      - name: Build Engagement Harness
        run: |
          cd /tmp/harness-review
          pnpm install --frozen-lockfile
          pnpm build

      - name: Install CLI
        run: |
          printf '#!/bin/sh\\nexec node /tmp/harness-review/packages/cli/dist/bin/engagement-harness.js "$@"\\n' | sudo tee /usr/local/bin/engagement-harness
          sudo chmod +x /usr/local/bin/engagement-harness

      - name: Restore findings cache
        uses: actions/cache@v3
        with:
          path: .engagement-harness/findings/
          key: known-findings-pr-\${{ github.event.pull_request.number }}
          restore-keys: |
            known-findings-pr-\${{ github.event.pull_request.number }}

      - name: Run review
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: \${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: \${{ github.repository }}
          GITHUB_PR_TITLE: \${{ github.event.pull_request.title }}
          GITHUB_PR_BODY: \${{ github.event.pull_request.body }}
        run: engagement-harness review --ci

      - name: Save findings cache
        if: always()
        uses: actions/cache@v3
        with:
          path: .engagement-harness/findings/
          key: known-findings-pr-\${{ github.event.pull_request.number }}

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: engagement-harness-reports
          path: .engagement-harness/reports/
`;

const GITHUB_ACTIONS_SOURCE_TEMPLATE = `# .github/workflows/engagement-harness.yml
# Generated by engagement-harness ci templates --platform github
name: Engagement Harness Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  review:
    name: PR Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '24'

      - name: Fetch base branch
        run: git fetch origin \${{ github.base_ref }}:\${{ github.base_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Install CLI
        run: |
          printf '#!/bin/sh\\nexec node %s/packages/cli/dist/bin/engagement-harness.js "$@"\\n' "$(pwd)" \\
            | sudo tee /usr/local/bin/engagement-harness
          sudo chmod +x /usr/local/bin/engagement-harness

      - name: Restore findings cache
        uses: actions/cache@v3
        with:
          path: .engagement-harness/findings/
          key: known-findings-pr-\${{ github.event.pull_request.number }}
          restore-keys: |
            known-findings-pr-\${{ github.event.pull_request.number }}

      - name: Run quality gates
        run: |
          pnpm lint
          pnpm typecheck
          pnpm test

      - name: Run review
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_PR_NUMBER: \${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: \${{ github.repository }}
          GITHUB_PR_TITLE: \${{ github.event.pull_request.title }}
          GITHUB_PR_BODY: \${{ github.event.pull_request.body }}
        run: engagement-harness review --ci

      - name: Save findings cache
        if: always()
        uses: actions/cache@v3
        with:
          path: .engagement-harness/findings/
          key: known-findings-pr-\${{ github.event.pull_request.number }}

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: engagement-harness-reports
          path: .engagement-harness/reports/
`;

const GITLAB_CI_TEMPLATE = `# .gitlab-ci.yml snippet
# Generated by engagement-harness ci templates --platform gitlab
engagement-harness-review:
  image: node:20
  stage: review
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    GITHUB_PR_NUMBER: '$CI_MERGE_REQUEST_IID'
    GITHUB_REPOSITORY: '$CI_PROJECT_PATH'
  script:
    - npm install -g pnpm
    - git clone https://oauth2:\${HARNESS_PAT}@github.com/abhishikthmeesala-2000/harness-review.git /tmp/harness-review
    - cd /tmp/harness-review && pnpm install --frozen-lockfile && pnpm build
    - printf '#!/bin/sh\\nexec node /tmp/harness-review/packages/cli/dist/bin/engagement-harness.js "$@"\\n' > /usr/local/bin/engagement-harness && chmod +x /usr/local/bin/engagement-harness
    - cd $CI_PROJECT_DIR
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY engagement-harness review --ci
  artifacts:
    when: always
    paths:
      - .engagement-harness/reports/
    expire_in: 30 days
`;

const AZURE_DEVOPS_TEMPLATE = `# azure-pipelines.yml snippet
# Generated by engagement-harness ci templates --platform azure-devops
trigger: none

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js 20'

  - script: npm install -g pnpm
    displayName: 'Install pnpm'

  - script: |
      git clone https://x-access-token:$(HARNESS_PAT)@github.com/abhishikthmeesala-2000/harness-review.git /tmp/harness-review
      cd /tmp/harness-review
      pnpm install --frozen-lockfile
      pnpm build
      printf '#!/bin/sh\\nexec node /tmp/harness-review/packages/cli/dist/bin/engagement-harness.js "$@"\\n' | sudo tee /usr/local/bin/engagement-harness
      sudo chmod +x /usr/local/bin/engagement-harness
    displayName: 'Build and install engagement-harness'

  - script: |
      git fetch origin $(System.PullRequest.TargetBranch):$(System.PullRequest.TargetBranch)
      engagement-harness review --ci
    displayName: 'Run engagement-harness review'
    env:
      ANTHROPIC_API_KEY: $(ANTHROPIC_API_KEY)
      GITHUB_PR_NUMBER: $(System.PullRequest.PullRequestNumber)
      GITHUB_REPOSITORY: $(Build.Repository.Name)

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '.engagement-harness/reports/'
      ArtifactName: 'engagement-harness-reports'
    displayName: 'Upload reports'
`;

const BITBUCKET_TEMPLATE = `# bitbucket-pipelines.yml snippet
# Generated by engagement-harness ci templates --platform bitbucket
pipelines:
  pull-requests:
    '**':
      - step:
          name: Engagement Harness Review
          image: node:20
          script:
            - npm install -g pnpm
            - git clone https://x-access-token:\${HARNESS_PAT}@github.com/abhishikthmeesala-2000/harness-review.git /tmp/harness-review
            - cd /tmp/harness-review && pnpm install --frozen-lockfile && pnpm build
            - printf '#!/bin/sh\\nexec node /tmp/harness-review/packages/cli/dist/bin/engagement-harness.js "$@"\\n' > /usr/local/bin/engagement-harness && chmod +x /usr/local/bin/engagement-harness
            - cd $BITBUCKET_CLONE_DIR
            - git fetch origin $BITBUCKET_PR_DESTINATION_BRANCH:$BITBUCKET_PR_DESTINATION_BRANCH
            - engagement-harness review --ci
          variables:
            ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY
          artifacts:
            - .engagement-harness/reports/**
`;

const FEEDBACK_ON_MERGE_TEMPLATE = `# .github/workflows/feedback-on-merge.yml
# Generated by engagement-harness ci templates --platform github
name: Collect Feedback on Merge

on:
  pull_request:
    types: [closed]

jobs:
  collect-if-merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: \${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '24'

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Clone Engagement Harness
        run: git clone https://\${{ secrets.HARNESS_PAT }}@github.com/abhishikthmeesala-2000/harness-review.git /tmp/harness

      - name: Build
        run: |
          cd /tmp/harness
          pnpm install --frozen-lockfile
          pnpm build

      - name: Install CLI
        run: |
          printf '#!/bin/sh\\nexec node /tmp/harness/packages/cli/dist/bin/engagement-harness.js "$@"\\n' \\
            | sudo tee /usr/local/bin/engagement-harness
          sudo chmod +x /usr/local/bin/engagement-harness

      - name: Collect feedback
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          engagement-harness feedback collect \\
            --repo \${{ github.repository }} \\
            --pr \${{ github.event.pull_request.number }}

      - name: Commit metrics
        run: |
          git config user.name "Engagement Harness Bot"
          git config user.email "engagement-harness[bot]@users.noreply.github.com"
          git add .engagement-harness/feedback/metrics.json 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No metrics changes to commit."
          else
            git commit -m "chore: update feedback from PR #\${{ github.event.pull_request.number }}"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
`;

const FEEDBACK_COLLECTION_TEMPLATE = `# .github/workflows/collect-feedback.yml
# Generated by engagement-harness ci templates --platform github
name: Weekly Feedback Sweep

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: \${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '24'

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Clone Engagement Harness
        run: git clone https://\${{ secrets.HARNESS_PAT }}@github.com/abhishikthmeesala-2000/harness-review.git /tmp/harness

      - name: Build
        run: |
          cd /tmp/harness
          pnpm install --frozen-lockfile
          pnpm build

      - name: Install CLI
        run: |
          printf '#!/bin/sh\\nexec node /tmp/harness/packages/cli/dist/bin/engagement-harness.js "$@"\\n' \\
            | sudo tee /usr/local/bin/engagement-harness
          sudo chmod +x /usr/local/bin/engagement-harness

      - name: Collect feedback
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          engagement-harness feedback collect \\
            --repo \${{ github.repository }} \\
            --days 7

      - name: Commit metrics
        run: |
          git config user.name "Engagement Harness Bot"
          git config user.email "engagement-harness[bot]@users.noreply.github.com"
          git add .engagement-harness/feedback/metrics.json 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No metrics changes to commit."
          else
            git commit -m "chore: weekly feedback update"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
`;

const TEMPLATES: Record<string, string> = {
  github: GITHUB_ACTIONS_CLIENT_TEMPLATE,
  gitlab: GITLAB_CI_TEMPLATE,
  'azure-devops': AZURE_DEVOPS_TEMPLATE,
  bitbucket: BITBUCKET_TEMPLATE,
};

const ALL_PLATFORMS = ['github', 'gitlab', 'azure-devops', 'bitbucket'] as const;

const OUTPUT_PATHS: Record<string, string> = {
  github: '.github/workflows/engagement-harness.yml',
  gitlab: '.gitlab-ci.yml',
  'azure-devops': 'azure-pipelines.yml',
  bitbucket: 'bitbucket-pipelines.yml',
};

export function writeFeedbackWorkflows(workflowDir: string): void {
  mkdirSync(workflowDir, { recursive: true });
  const onMergePath = `${workflowDir}/feedback-on-merge.yml`;
  const collectPath = `${workflowDir}/collect-feedback.yml`;
  writeFileSync(onMergePath, FEEDBACK_ON_MERGE_TEMPLATE, 'utf8');
  console.log(`Written to ${onMergePath}`);
  writeFileSync(collectPath, FEEDBACK_COLLECTION_TEMPLATE, 'utf8');
  console.log(`Written to ${collectPath}`);
}

export function generateGithubWorkflow(cwd: string): string {
  const ctx = isSourceRepo(cwd) ? 'source' : 'client';
  return ctx === 'source' ? GITHUB_ACTIONS_SOURCE_TEMPLATE : GITHUB_ACTIONS_CLIENT_TEMPLATE;
}

export function ciTemplatesCommand(options: CiTemplatesOptions): void {
  const { platform, write, context = 'auto' } = options;
  const shouldPrint = options.print !== false;

  if (!platform) {
    if (shouldPrint) {
      for (const name of ALL_PLATFORMS) {
        console.log(`\n# ===== ${name.toUpperCase()} =====\n`);
        console.log(TEMPLATES[name]);
      }
    }
    return;
  }

  const template = TEMPLATES[platform];
  if (!template) {
    console.error(
      `Unknown platform "${platform}". Supported platforms: ${ALL_PLATFORMS.join(', ')}`,
    );
    process.exit(1);
    return;
  }

  // For github, resolve context to pick the right template
  const resolvedTemplate =
    platform === 'github'
      ? context === 'source'
        ? GITHUB_ACTIONS_SOURCE_TEMPLATE
        : context === 'client'
          ? GITHUB_ACTIONS_CLIENT_TEMPLATE
          : generateGithubWorkflow(process.cwd())
      : template;

  // GitHub: write to disk by default (--no-write to override).
  // All other platforms: print to stdout by default (--write to save).
  const shouldWrite = write ?? platform === 'github';

  if (shouldWrite) {
    const outPath = OUTPUT_PATHS[platform]!;
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, resolvedTemplate, 'utf8');
    console.log(`Written to ${outPath}`);
    if (platform === 'github') {
      writeFeedbackWorkflows('.github/workflows');
    }
  } else if (shouldPrint) {
    console.log(resolvedTemplate);
    if (platform === 'github') {
      console.log('\n# ===== FEEDBACK ON MERGE WORKFLOW =====\n');
      console.log(FEEDBACK_ON_MERGE_TEMPLATE);
      console.log('\n# ===== WEEKLY FEEDBACK SWEEP WORKFLOW =====\n');
      console.log(FEEDBACK_COLLECTION_TEMPLATE);
    }
  }
}
